[project]
name = "vqvae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "torchvision>=0.23.0",
    "tqdm>=4.67.1",
    "vector-quantize-pytorch>=1.23.2",
]
